name: yrs_jdshop
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^1.0.2
  dio: ^2.2.2
  shared_preferences: ^0.5.3
  flutter_inappbrowser: ^1.2.2
  provider: ^3.2.0
  event_bus: ^1.1.1
  fluttertoast: ^3.1.3
  city_pickers: ^0.1.30
  crypto: ^2.1.4
  flutter_ijkplayer: ^0.3.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/user_bg.jpg
    - images/user.png
  
